# Project identification
sonar.projectKey=taller3
sonar.projectName=taller3
sonar.projectVersion=1.0

# Project metadata
sonar.language=py
sonar.sources=.

# Paths to source directories (relative to the project root)
sonar.inclusions=app.py

# Encoding of the source files
sonar.sourceEncoding=UTF-8

# Python properties
sonar.python.version=3.11

# Authentication
sonar.login=sqp_caaac6c2f8e91a0282a60e34de1ddac28ed14315


sonar.scm.disabled=true

sonar.python.coverage.reportPaths=coverage.xml
